version: '3.8'

services:
    docusaurus:
        build:
            context: .
            dockerfile: ./.docker/Dockerfile
        ports:
            - "80:80"
        volumes:
            - .:/app
            - /app/node_modules
        environment:
            - NODE_ENV=development
